# Generated by Django 3.1.4 on 2022-06-26 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220626_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referaluser',
            name='refer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Refer_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
